egg-full-demo:
  image: egg-full-demo
  links:
    - mysql:egg-mysql-server
    - redis:egg-redis-server
  ports:
    - "7001:7001"
  volumes:
    - ./volume:/app/volume

mysql:
  image: mysql:5.7
  container_name: egg-mysql-server
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=neo
  
redis:
  image: redis:3.2
  container_name: egg-redis-server
  environment:
    - PASSWORD=neo
  volumes:
    - ./redis:/data

